version: '3.7'
services:
  api:
    build: .
    container_name: api
    network_mode: host
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    env_file:
    - .env
    environment:
      NODE_ENV: development
    command: sh -c "yarn install && yarn dev"
    restart: unless-stopped
